version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_NODE_ENV: ${VITE_NODE_ENV:-production}
        VITE_RECAPTCHA_SITE_KEY: ${VITE_RECAPTCHA_SITE_KEY}
    expose:
      - 5000
    environment:
      NODE_ENV: production
      PORT: 5000
      FRONTEND_URL: ${FRONTEND_URL}
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.gabtrotter.rule=Host(`${APP_DOMAIN}`) || Host(`www.${APP_DOMAIN}`)
      - traefik.http.routers.gabtrotter.entrypoints=websecure
      - traefik.http.routers.gabtrotter.tls.certresolver=letsencrypt
      - traefik.http.services.gabtrotter.loadbalancer.server.port=5000

networks:
  dokploy-network:
    external: true
